# Site
name: "Jimmy Chen's Blog"
description: "Blogging fo my life & coding"
meta_description: "Jekyll template, Medium styled, free for bloggers."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ""
#google_analytics: 'UA-46278016-1'
disqus: 'my-github-pages'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

url: "https://jimmychen.space" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: Jimmy_Zju
github_username:  cjmdaixi

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown
highlighter: rouge